### ISSUE TITLE
Crash on Unicode characters

### ISSUE THREAD

**Issue by JurgenG** [Busindre/dumpzilla#1]
When running the script (Ubuntu 17.10 - Python 3.7) I'm getting this error:

```
Last visit: 2017-09-24 19:14:25
Traceback (most recent call last):
  File "dumpzilla.py", line 1145, in <module>
    All_execute(varDir)
  File "dumpzilla.py", line 215, in All_execute
    show_history_firefox(varDir)
  File "dumpzilla.py", line 619, in show_history_firefox
    print('Title: %s' % row[1])
UnicodeEncodeError: 'ascii' codec can't encode character '\xa0' in position 8: ordinal not in range(128)
```
Maybe a simple "try/catch could circumvent this crash allowing it not to crash but to continue on the rest of the process.
It's not only with character \xa0 but with several characters.

**Comment by onehdev** [comment]
Could you try with the new version to see if already solved?

**Comment by JurgenG** [comment]
My apologies. It seems that I didn't have that master branch.
Unfortunately, I can't try it, as I'm getting an error on the LZ4 library.
I'll file a new bug as this is something completely different.

**Comment by onehdev** [comment]
No problem! With the new version (merged a few days ago), this UnicodeEncodeError problem may be solved. To check it out you can bypass that LZ4 error by retrieving only the profile History (it looks like the UnicodeEncodeError was thrown in this section). 

Please, try to execute Dumpzilla by this way to retrieve only the History:

`python3 dumpzilla.py <profile_path> --History`

Thanks!

**Comment by JurgenG** [comment]
Hi,
thanks for sharing the commits! The UnicodeEncodeError appears to be resolved. I'm really looking forward on your progress on the other aspects too...
